[package]
name = "neural_network"
version = "0.1.0"
description = "A minimal template for developing with Cairo 1.0"
homepage = "https://github.com/auditless/cairo-template"

[dependencies]
onnx_cairo = { git = "https://github.com/franalgaba/onnx-cairo" }

[scripts]
test = "cairo-test -p ."
cairo = "cairo-run -p ."